### ISSUE TITLE
Typescript Definitions

### ISSUE THREAD

**Issue by sheuertz** [guisturdy/dayjs-plugin-utc#3]
Hi,

I'm trying to use this in my typescript project, but there are no type definitions.

Thanks.

**Comment by victorcarvalhosp** [comment]
Why this is closed? I'm having the same issue, when I try to use it on my react project I got the following error:
ts 7016 Could not find a declaration file for module 'dayjs-plugin-utc'. '/path/to/module-name.js' implicitly has an 'any' type

**Comment by Epistol** [comment]
Bump, no ts definition.

**Comment by shriharip** [comment]
sorry, but I don't think this is solved right. I do not see the definitions file and facing the same issue.

**Comment by LukasDeco** [comment]
And I am here another person saying there are no ts types....
