### ISSUE TITLE
`startOf` breaks offset 

### ISSUE THREAD

**Issue by roadmanfong** [guisturdy/dayjs-plugin-utc#4]
Hi, 

Thank you for creating this plugin, but I found some issue with `.startOf`. 

```js
const b = dayjs.utc('2010-2-2 12:0:0').utcOffset(-450)
b.format('YYYY-MM-DD HH:mm')
// "2010-02-02 04:30"

b.hour()
// 4
b.startOf('hour').hour()
// 20 -> should be 4

b.startOf('hour').format('YYYY-MM-DD HH:mm')
// "2010-02-02 20:00" -> should be  // "2010-02-02 04:00"
b.startOf('minute').format('YYYY-MM-DD HH:mm')
// "2010-02-02 20:00" -> should be  // "2010-02-02 04:00"


b.startOf('minute').utcOffset(-450).format('YYYY-MM-DD HH:mm')
// "2010-02-02 04:30" -> works well if added `.utcOffset` again

```

**Comment by danazkari** [comment]
I haven't had the time to read through the entire documentation but would this be fixed if the function 'startOf' is added to this line?

https://github.com/guisturdy/dayjs-plugin-utc/blob/ebe2606be6b4eb7d53846d67b74008ad59a58677/src/index.js#L7

My guess is it isn't this simple, but just wanted to get the conversation going, and perhaps a PR can come out of this 😄

**Comment by danazkari** [comment]
Added a PR #5, hope this helps, I added a test and it seemed to pass with flying colors, @guisturdy please tell me if I'm missing something, I really REALLY need this fix in order to get rid of momentJS and trim some precious KBs off of my project gzipped build.

**Comment by guisturdy** [comment]
Sorry to reply so late, I will deal with this later.

**Comment by danazkari** [comment]
sure @guisturdy don't worry about it, just please let me know if there's anything I'm missing on my PR so I can work on it.

Yo @roadmanfong can you take a look at the PR and give it a look and see if it fixes your issue? It did for me 😄
